### ISSUE TITLE
Cannot easily clone this repo in Windows due to illegal characters in some filenames

### ISSUE THREAD

**Issue by rcgoff** [besm6/besm6.github.io#11]
In the folder [wiki/to-be-restored](https://github.com/besm6/besm6.github.io/tree/master/wiki/to-be-restored) there are files:
`мониторная система "дубна".txt`
`пакетный редактор *edit.txt`
`инструкция dms, старый вариант.txt`
`микро-бэсм, или мкб-8601.txt`,
whose names are illegal in Windows. This makes it difficult to clone repo under windows...

**Comment by sergev** [comment]
Fixed in https://github.com/besm6/besm6.github.io/commit/9c403f7ae2b786182f9df54a7de9c7aaa9388166.

**Comment by rcgoff** [comment]
Merci beaucoup!
