### ISSUE TITLE
Please add a link to besm6.github.io in the repository description

### ISSUE THREAD

**Issue by jpluimers** [besm6/besm6.github.io#22]
Since this is a repository property, I cannot create a pull-request for it:

Please add a link to [besm6.github.io](https://besm6.github.io) to the repository "About" section.

That makes it easier to navigate from the repository to the actual site.

To do this as a maintainer:

1. navigate to https://github.com/besm6/besm6.github.io
2. next to "About" click on the icon
3. in the pop-up under "Website" enter `https://besm6.github.io`

**Comment by sergev** [comment]
Done!
Thank you, Jeroen.
